version: '3.9'

services:
  postgres:
    image: postgres:17.4
    container_name: stock-system-postgres
    environment:
      POSTGRES_USER: stockuser
      POSTGRES_PASSWORD: stockpassword
      POSTGRES_DB: stockdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  fastapi:
    build: ./stock-system-marketdata
    container_name: stock-system-marketdata
    restart: always
    ports:
      - "8001:8001"
    depends_on:
      - postgres
  backend:
    build: ./stock-system-backend
    container_name: stock-system-backend
    restart: always
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockdb
      SPRING_DATASOURCE_USERNAME: stockuser
      SPRING_DATASOURCE_PASSWORD: stockpassword
    depends_on:
      - postgres
  frontend:
    build: ./stock-system-frontend
    container_name: stock-system-frontend
    ports:
      - "3001:80"
    depends_on:
      - backend
volumes:
  postgres-data: